CREATE DATABASE IF NOT EXISTS games;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(80) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX (email)
) ENGINE=INNODB;